[package]
name = "miminal_app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
opt-level = "s"
codegen-units = 1

[dependencies]
x86 = "0.52.0"

