[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.minimal_compile]
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[build]
target = "minimal_compile.json"


