[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
# target = "min_two.json"
target = "minimal_compile.json"
rustflags = ["-C", "link-args=-nostartfiles -nostdlib -ffreestanding"]
