[package]
name = "vmm_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
kvm-bindings = "0.6.0"
libc = "0.2.149"
vmm-sys-util = "0.11.2"
